name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Cache generated recipes data
        uses: actions/cache@v4
        with:
          path: src/generated/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/generated/*.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build and test
        run: |
          yarn
          yarn build
