name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Cache generated recipes data
        uses: actions/cache@v4
        with:
          path: src/generated/
          key: recipes-cache-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/generated/*.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build and test
        run: |
          yarn
          yarn build
