name: Build

on:
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and test
        run: |
          yarn
          yarn build
